#ifndef __LOPHTWARE_USBCPIC32BREAKOUT_FIRMWARE_BOARDVARIANTS_USBCC_H
#define __LOPHTWARE_USBCPIC32BREAKOUT_FIRMWARE_BOARDVARIANTS_USBCC_H

#ifdef BOARD_VARIANT_LITE
#include "Lite/UsbCc.h"
#else
#include "FullFat/UsbCc.h"
#endif

#endif
