#ifndef __LOPHTWARE_USBCPIC32BREAKOUT_FIRMWARE_VERSION_H
#define __LOPHTWARE_USBCPIC32BREAKOUT_FIRMWARE_VERSION_H

#define VERSION_FIRMWARE_FLAGS 0x00
#define VERSION_FIRMWARE_MAJOR 1
#define VERSION_FIRMWARE_MINOR 1
#define VERSION_FIRMWARE_REVISION 0

#define VERSION_FIRMWARE_AS_WORD ( \
	(VERSION_FIRMWARE_FLAGS << 24) | \
	(VERSION_FIRMWARE_MAJOR << 16) | \
	(VERSION_FIRMWARE_MINOR << 8) | \
	(VERSION_FIRMWARE_REVISION << 0))

#define VERSION_FIRMWARE_MAJOR_MINOR_FROM(v) ((v) & 0x00ffff00ul)

#define VERSION_USB_API_MAJOR 1
#define VERSION_USB_API_MINOR 0

#define TO_BCD(x) ((((x) / 10) << 4) | ((x) % 10))

#define VERSION_USB_API_MAJOR_BCD TO_BCD(VERSION_USB_API_MAJOR)
#define VERSION_USB_API_MINOR_BCD TO_BCD(VERSION_USB_API_MINOR)

#define VERSION_USB_API_AS_WORD ( \
	(VERSION_USB_API_MAJOR << 24) | \
	(VERSION_USB_API_MINOR << 16) | \
	(VERSION_USB_API_MAJOR_BCD << 8) | \
	(VERSION_USB_API_MINOR_BCD << 0))

#endif
