#ifndef __LOPHTWARE_USBCPIC32BREAKOUT_FIRMWARE_USB_USBCONFIG_H
#define __LOPHTWARE_USBCPIC32BREAKOUT_FIRMWARE_USB_USBCONFIG_H

#define NUM_ENDPOINT_NUMBERS 10
#define EP_0_LEN 64

#define CORE_INTERFACE_ID 0
#define CORE_EP_ID (CORE_INTERFACE_ID + 1)
#define EP_1_IN_LEN 64
#define EP_CORE_IN_LEN EP_1_IN_LEN
#define EP_1_OUT_LEN 64
#define EP_CORE_OUT_LEN EP_1_OUT_LEN

#define TIMER_INTERFACE_ID 1
#define TIMER_EP_ID (TIMER_INTERFACE_ID + 1)
#define EP_2_IN_LEN 8
#define EP_TIMER_IN_LEN EP_2_IN_LEN
#define EP_2_OUT_LEN 0

#define CCP_INTERFACE_ID 2
#define CCP_EP_ID (CCP_INTERFACE_ID + 1)
#define EP_3_IN_LEN 8
#define EP_CCP_IN_LEN EP_3_IN_LEN
#define EP_3_OUT_LEN 0

#define USB_INTERFACE_ID 3
#define USB_EP_ID (USB_INTERFACE_ID + 1)
#define EP_4_IN_LEN 64
#define EP_USB_IN_LEN EP_4_IN_LEN
#define EP_4_OUT_LEN 64
#define EP_USB_OUT_LEN EP_4_OUT_LEN

#define I2C_INTERFACE_ENABLED
#define I2C_INTERFACE_ID 4
#define I2C_EP_ID (I2C_INTERFACE_ID + 1)
#define EP_5_IN_LEN 64
#define EP_I2C_IN_LEN EP_5_IN_LEN
#define EP_5_OUT_LEN 64
#define EP_I2C_OUT_LEN EP_5_OUT_LEN

#define UART_INTERFACE_ID 5
#define UART_EP_ID (UART_INTERFACE_ID + 1)
#define EP_6_IN_LEN 64
#define EP_UART_IN_LEN EP_6_IN_LEN
#define EP_6_OUT_LEN 64
#define EP_UART_OUT_LEN EP_6_OUT_LEN

#define SPI_INTERFACE_ENABLED
#define SPI_INTERFACE_ID 6
#define SPI_EP_ID (SPI_INTERFACE_ID + 1)
#define EP_7_IN_LEN 64
#define EP_SPI_IN_LEN EP_7_IN_LEN
#define EP_7_OUT_LEN 64
#define EP_SPI_OUT_LEN EP_7_OUT_LEN

#define ADC_INTERFACE_ID 7
#define ADC_EP_ID (ADC_INTERFACE_ID + 1)
#define EP_8_IN_LEN 64
#define EP_ADC_IN_LEN EP_8_IN_LEN
#define EP_8_OUT_LEN 0

#define DAC_INTERFACE_ID 8
#define DAC_EP_ID 0

#define COMPARATOR_INTERFACE_ID 9
#define COMPARATOR_EP_ID COMPARATOR_INTERFACE_ID
#define EP_9_IN_LEN 8
#define EP_COMPARATOR_IN_LEN EP_9_IN_LEN
#define EP_9_OUT_LEN 0

#define CLC_INTERFACE_ID 10
#define CLC_EP_ID CLC_INTERFACE_ID
#define EP_10_IN_LEN 8
#define EP_CLC_IN_LEN EP_10_IN_LEN
#define EP_10_OUT_LEN 8
#define EP_CLC_OUT_LEN EP_10_OUT_LEN

#define NUMBER_OF_CONFIGURATIONS 1
#define NUMBER_OF_INTERFACES 11

#define PPB_MODE PPB_ALL
#define USB_USE_INTERRUPTS
#define USB_NEEDS_POWER_ON
#define SFR_USB_POWER U1PWRCbits.USBPWR

#define USB_DEVICE_DESCRIPTOR usbDeviceDescriptor
#define USB_CONFIG_DESCRIPTOR_MAP usbConfigurationDescriptors
#define USB_STRING_DESCRIPTOR_FUNC usbOnGetStringDescriptor

#define SET_CONFIGURATION_CALLBACK usbOnSetConfiguration
#define GET_DEVICE_STATUS_CALLBACK usbOnGetDeviceStatus
#define ENDPOINT_HALT_CALLBACK usbOnEndpointHalt
#define SET_INTERFACE_CALLBACK usbOnSetInterface
#define GET_INTERFACE_CALLBACK usbOnGetInterface
#define OUT_TRANSACTION_CALLBACK usbOnOutTransaction
#define IN_TRANSACTION_COMPLETE_CALLBACK usbOnInTransaction
#define UNKNOWN_SETUP_REQUEST_CALLBACK usbOnUnknownSetupRequest
#define UNKNOWN_GET_DESCRIPTOR_CALLBACK usbOnGetUnknownDescriptor
#define USB_RESET_CALLBACK usbOnReset

#define USB_HID_DESCRIPTOR_FUNC usbHidOnGetDescriptor
#define USB_HID_REPORT_DESCRIPTOR_FUNC usbHidOnGetReportDescriptor

#define HID_GET_REPORT_CALLBACK usbHidOnGetReport
#define HID_SET_REPORT_CALLBACK usbHidOnSetReport
#define HID_GET_IDLE_CALLBACK usbHidOnGetIdle
#define HID_SET_IDLE_CALLBACK usbHidOnSetIdle
#define HID_GET_PROTOCOL_CALLBACK usbHidOnGetProtocol
#define HID_SET_PROTOCOL_CALLBACK usbHidOnSetProtocol

#define USB_INTERRUPT_PROTOTYPE_ONLY
#define _USB_1_VECTOR _USB_VECTOR

#endif
